variables:
  - name: deploymentRegion
    value: canadacentral
  - name: serviceConnection
    value: AzureLabCACN-MSDN
  - name: vmWinImage
    value: windows-latest
  - name: vmImage
    value: ubuntu-latest
  - name: deployOperation
    value: create
stages:
  - stage: Deploy_AVD_Accelerator
    displayName: Deploy AVD Accelerator
    jobs:
      # Deploy template deploy.bicep for AVD Accelerator
      - template: ../jobs/deploy-template-sub.yml
        parameters:
          jobName: Deploy_AVD_Accelerator
          location: $(deploymentRegion)
          workingDir: $(System.DefaultWorkingDirectory)/workload
          templateFile: deploy.bicep
          parameterArray:
            - resourceGroupName AVD-${{ parameters.personaId }}-RG
            - resourceGroupLocation $(deploymentRegion)
