trigger:
  - none

pr:
  - none

variables:
  - name: deploymentRegion
    value: canadacentral
  - name: serviceConnection
    value: AzureLabCACN-MSDN
  - name: vmWinImage
    value: windows-latest
  - name: vmImage
    value: ubuntu-latest
  - name: deployOperation
    value: create
  - name: var-bashPostInjectScript
    value: ':'
  - name: var-bashPreInjectScript
    value: 'set -E; function catch { echo "##vso[task.logissue type=error]Caller: $(caller), LineNo: $LINENO, Command: $BASH_COMMAND" ; exit 1 ; } ; echo ; echo "Current working directory: $(pwd)" ; echo ; trap catch ERR'
  - name: avdShrdlSubscriptionId
    value: 4f6c98e1-04a4-49f0-abce-6240b1726c3f
  - name: avdWrklSubscriptionId
    value: 4f6c98e1-04a4-49f0-abce-6240b1726c3f
  - name: avdWrklSecretAccess
    value: 8e23a491-5178-4c69-9fce-1377e52a29c6

stages:
  - stage: Deploy_AVD_Accelerator
    displayName: Deploy AVD Accelerator
    jobs:
      # Deploy template deploy.bicep for AVD Accelerator
      - template: deploy-template-sub.yml
        parameters:
          jobName: Deploy_AVD_Accelerator
          location: $(deploymentRegion)
          workingDir: $(System.DefaultWorkingDirectory)/workload
          templateFile: deploy.bicep
          parameterArray:
            - avdShrdlSubscriptionId $(avdShrdlSubscriptionId)
            - avdWrklSubscriptionId $(avdWrklSubscriptionId)
            - location $(deploymentRegion)
            - avdWrklSecretAccess $(avdWrklSecretAccess)
            - useSharedImage true
            - avdOsImage win11-21h2