variables:
  - name: deploymentRegion
    value: canadacentral
  - name: serviceConnection
    value: AzureLabCACN-MSDN
  - name: vmWinImage
    value: windows-latest
  - name: vmImage
    value: ubuntu-latest
  - name: deployOperation
    value: create

  - name: avdShrdlSubscriptionId
    value: 4f6c98e1-04a4-49f0-abce-6240b1726c3f
  - name: avdWrklSubscriptionId
    value: 4f6c98e1-04a4-49f0-abce-6240b1726c3f

stages:
  - stage: Deploy_AVD_Accelerator
    displayName: Deploy AVD Accelerator
    jobs:
      # Deploy template deploy.bicep for AVD Accelerator
      - template: deploy-template-sub.yml
        parameters:
          jobName: Deploy_AVD_Accelerator
          location: $(deploymentRegion)
          workingDir: $(System.DefaultWorkingDirectory)/workload
          templateFile: deploy.bicep
          parameterArray:
            - avdShrdlSubscriptionId ($avdShrdlSubscriptionId)
            - avdWrklSubscriptionId ($avdWrklSubscriptionId)
            - location $(deploymentRegion)
